### ISSUE TITLE
Push notifications in browsers

### ISSUE THREAD

**Issue by eliduvid** [MoeraOrg/moera-issues#279]
Add an option to send notifications directly to browser with web push notification API.

As I see it, there should be button "Subscribe for push notifications" in menu. And obviously you shouldn't be able to subscribe to other's notifications.

There is pretty easy-to-follow instruction on how to do it https://golb.hplar.ch/2019/08/webpush-java.html

I think it should help implementing push notifications for mobile app in the future.

**Comment by eliduvid** [comment]
@smelamud, it's mostly server code, I think, so node label should be there too.

**Comment by miqueasgutierrez** [comment]
Simple instructions so that you can integrate notifications on your website.
1.Create an account (free, no credit card required).
https://indigitall.com/latinoamerica/plan-free-1006/

2. Paste the following code on the main page of your website, just before the end of the </body> tag:
Important: the appKey value is unique and personal. You can get it by accessing your account> settings> App Key value
`<script
  src = "/ sdk.min.js"
  onload = "indigitall.init ({
    appKey: 'yourAppKeyHere',
    workerPath: '/worker.min.js',
    requestLocation: true
  }) "
  async>
</script>`

3.Download .zip and extract its two files to upload them to the main folder of your website.
https://storage.googleapis.com/indigitall-public-assets/sdk/webpush/indigitallWebpush_v3.4.1.zip

Check the integration

If everything went well, when you access your website again, you should see a message in your browser to allow notifications. Example: https://docs.indigitall.com/images/setup_javascript_1.png

here you can see the complete guide.  https://docs.indigitall.com/indigitallsetup/webpushquickstart/javascript.html

**Comment by smelamud** [comment]
Done.
