### ISSUE TITLE
Scroll news feed when "news" button pressed

### ISSUE THREAD

**Issue by grep0** [MoeraOrg/moera-issues#318]
Suggestion: when a user clicks "news" icon with a number, scroll the news feed up to make the newly arrived news visible. Also highlight the new news.

**Comment by smelamud** [comment]
Should the feed be positioned on the latest or on the earliest of new posts?

Another thing that bothers me: if user leaves the News page and then returns to it by clicking the "news" button, the feed should be shown at the same position it was when the user left it. Otherwise, this will create confusion. I would recommend in this situation to scroll to the new posts only by second click by "news" icon, when the user is already on the News page. This is the behavior similar to Telegram.

**Comment by grep0** [comment]
It definitely should **not** stay at the same location with minimum interface decoration change as it currently does. And yes, I only care of the case of clicking "news" when we are already on the news page.

As for highlighting, some slight background color highlight (like #ffffcc) for new items would be great

**Comment by smelamud** [comment]
Done.
