### ISSUE TITLE
Standalone mode of the client

### ISSUE THREAD

**Issue by smelamud** [MoeraOrg/moera-issues#64]
Implement standalone mode of the client: if the client is opened from [client.moera.org](http://client.moera.org) directly, we switch to "hello screen". Then the current node is selected in the search bar and the current path is set after `#!` in the URL. When clicking links, the client sends `OPTIONS` request to the target. If `X-Moera` header is returned, the internal redirect is made with a new API root.

**Comment by tigra** [comment]
I.e. this will allow using Moera without having the browser extension set up?
And, the URLs will be not indexable by search engines (which is good - because we don't create extra entries with same content which may be harmful for SEO).
Then I believe this is important, it lowers the barrier of entry.

**Comment by smelamud** [comment]
I've [described the drawbacks of this approach](http://moera.org/overview/browser-extension.html) and they are serious. Including sharing of URLs that contain a client in the address.

And I don't think the extension is hard to install, so it is a big barrier for entry. Yes, it is slightly unusual.

**Comment by smelamud** [comment]
We really need this as a temporary solution for mobile clients.

**Comment by smelamud** [comment]
Done.
